version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "cargo"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "Nayrosk"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "Nayrosk"
